### ISSUE TITLE
Update verions of seldon, subordinate images

### ISSUE THREAD

**Issue by ca-scribner** [canonical/seldon-core-operator#21]
`SeldonDeployment`s using our charm to deploy models from artifacts stored via mlflow currently fail to deploy because the `seldonio/mlflowserver:1.9.0` image used for the `classifier` pod has an unpinned package dependency problem.  This causes the flask server to fail like in pallets/flask#4455.  This has been fixed in SeldonIO/seldon-core#3946, which would fix new versions of the `mlflowserver` image.

To fix the above issue, we should update the images we specify in our config like here: https://github.com/canonical/seldon-core-operator/blob/c4aae1d0b0df3dc06bc1ad500daa21a5945b4f5d/src/templates/configmap.yaml#L19.  It is unclear if we need to update all images at the same time, or if we can pick and choose (for example, the main charm runtime is back on version 1.6, and current versions are >1.13.x)

**Comment by ca-scribner** [comment]
After some testing, I don't see any signs that seldon actually uses the configmap we deploy.  It is mounted to the manager pod, but when I've made changes to the content (changing the mlflowserver's image version) I don't see those reflected in what actually gets deployed, even if I delete the management pod so it restarts.  Is there somewhere else this is used, or is this more a reference file?

Looking at upstream, I don't see where they actually utilize this file.  They have it in [their manifests](https://github.com/SeldonIO/seldon-core/tree/master/operator/config/manager) and deploy it, but nothing cites it anywhere.  Does that mean there's something hard coded to load it from the manager?  If yes, we might have it incorrectly named (if I render the upstream manifests, the configmap is called `seldon-config` so might be that it needs that hard coded name?).

**Comment by ca-scribner** [comment]
As a patch, to get around the error described above by the unpinned version in mlflowserver, that is just a default image that is used to run the classifier.  Users can in their `seldondeployment` override it by doing:
```
apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: mlflow
spec:
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - name: classifier
          image: seldonio/mlflowserver:1.14.0-dev  # <--whatever version they want.  1.14.0-dev is patched for this bug
...
```
